# Implementation of Perceptron in Python:
- It is a Simplest ANN Architecture and the Probabilistic Model for Information Storage and Organization in the Brain.
- It is a Single Layer Perceptron which can learn only Linearly Seperable Patterns.
- Easy to Implement and Low Computation Power.
- Perceptrons can implement Logic Gates like AND,OR
- The Output of Perceptron can take only Binary Values (0 and 1) due to the Hard-Limit Activation Function.
- We use Step Function as an Activation.
- Perceptrons can only classify Linearly Seperable Sets of Vectors.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
class Perceptron:
  def __init__(self, eta, epochs):
    self.weights = np.random.randn(3) * 1e-4
    print(f"self.weights: {self.weights}")
    print('==============================================')
    self.eta = eta
    self.epochs = epochs

  def activationFunction(self, inputs, weights):
    z = np.dot(inputs, weights)
    return np.where(z > 0 , 1, 0)

  def fit(self, X, y):
    self.X = X
    self.y = y

    X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))] # concactination
    print(f"X_with_bias: \n{X_with_bias}")

    for epoch in range(self.epochs):
      print(f"for epoch: {epoch}")
      y_hat = self.activationFunction(X_with_bias, self.weights)
      print(f"predicted value: \n{y_hat}")
      error = self.y - y_hat
      print(f"error: \n{error}")
      self.weights = self.weights + self.eta * np.dot(X_with_bias.T, error)
      print(f"updated weights: \n{self.weights}")
      print('==============================================')

  def predict(self, X):
    X_with_bias = np.c_[X, -np.ones((len(self.X), 1))]
    return self.activationFunction(X_with_bias, self.weights)

## 1. AND Operation

In [3]:
data={"x1":[0,0,1,1],"x2":[0,1,0,1],"y":[0,0,0,1]}

In [4]:
AND=pd.DataFrame(data)
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [5]:
X=AND.drop("y",axis=1)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [6]:
y=AND["y"]
y.to_frame()

y
0  0
1  0
2  0
3  1

In [7]:
model=Perceptron(eta=0.5,epochs=10)
model.fit(X,y)

self.weights: [ 2.54473175e-04 -9.48486604e-05  5.89238254e-05]
X_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value: 
[0 0 1 1]
error: 
0    0
1    0
2   -1
3    0
Name: y, dtype: int64
updated weights: 
[-4.99745527e-01 -9.48486604e-05  5.00058924e-01]
for epoch: 1
predicted value: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: 
[2.54473175e-04 4.99905151e-01 5.89238254e-05]
for epoch: 2
predicted value: 
[0 1 1 1]
error: 
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights: 
[-4.99745527e-01 -9.48486604e-05  1.00005892e+00]
for epoch: 3
predicted value: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: 
[2.54473175e-04 4.99905151e-01 5.00058924e-01]
for epoch: 4
predicted value: 
[0 0 0 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[2.54473175e-04 4.99905151e-01 5.00058924e-01]
for epoch: 5
predicted value: 
[0 0

In [8]:
model.predict(X)

array([0, 0, 0, 1])

In [9]:
model.weights

array([2.54473175e-04, 4.99905151e-01, 5.00058924e-01])

## 2. OR Operation

In [10]:
data2={"x1":[0,0,1,1],"x2":[0,1,0,1],"y":[0,1,1,1]}

In [11]:
OR=pd.DataFrame(data2)

In [12]:
OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [13]:
X=OR.drop("y",axis=1)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [14]:
y=OR["y"]

In [15]:
y.to_frame()

y
0  0
1  1
2  1
3  1

In [16]:
model.fit(X,y)

X_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value: 
[0 0 0 1]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights: 
[ 0.50025447  0.99990515 -0.49994108]
for epoch: 1
predicted value: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[5.00254473e-01 9.99905151e-01 5.89238254e-05]
for epoch: 2
predicted value: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[5.00254473e-01 9.99905151e-01 5.89238254e-05]
for epoch: 3
predicted value: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[5.00254473e-01 9.99905151e-01 5.89238254e-05]
for epoch: 4
predicted value: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[5.00254473e-01 9.99905151e-01 5.89238254e-05]
for epoch: 5
predicted value: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights

In [17]:
model.predict(X)

array([0, 1, 1, 1])

In [18]:
model.weights

array([5.00254473e-01, 9.99905151e-01, 5.89238254e-05])

## 3. XOR Operation

In [19]:
data3={"x1":[0,0,1,1],"x2":[0,1,0,1],"y":[0,1,1,0]}

In [20]:
XOR=pd.DataFrame(data3)

In [21]:
X=XOR.drop("y",axis=1)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [22]:
y=XOR['y']
y

0    0
1    1
2    1
3    0
Name: y, dtype: int64

In [23]:
model=Perceptron(eta=0.5,epochs=100)

self.weights: [-3.14507111e-06  1.75642240e-04 -7.63107492e-06]


In [24]:
model.fit(X,y)

X_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights: 
[-0.50000315 -0.49982436  0.99999237]
for epoch: 1
predicted value: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights: 
[-3.14507111e-06  1.75642240e-04 -7.63107492e-06]
for epoch: 2
predicted value: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights: 
[-0.50000315 -0.49982436  0.99999237]
for epoch: 3
predicted value: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights: 
[-3.14507111e-06  1.75642240e-04 -7.63107492e-06]
for epoch: 4
predicted value: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights: 
[-0.50000315 -0.49982436  0.99999237]
for epoch: 5
predicted value: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights: 
[-3.14507

In [25]:
model.predict(X)

array([1, 1, 1, 1])

- Hence we can say that we are not able to give correct results with the help **Perceptron** for **XOR**.

In [26]:
model.weights

array([-3.14507111e-06,  1.75642240e-04, -7.63107492e-06])

- Here we can see Perceptron can only classify the linear problem like AND, OR operation because they were linear problem. But in the case of XOR it couldn't classify correctly because it was a non-linear problem. Lets see graphically.