# PyTorch

In [ ]:
import torch

- PyTorch is a library for processing tensors. A tensor is a number, vector, matrix or any n-dimensional array

In [ ]:
# Number
t1 = torch.tensor(4.)
t1

tensor(4.)

In [ ]:
t1.dtype

torch.float32

In [ ]:
# Vector(Array)
t2=torch.tensor([1.,2.,3.,4.])
t2

tensor([1., 2., 3., 4.])

In [ ]:
t2.dtype

torch.float32

In [ ]:
# Matrix
t3=torch.tensor([[5.,6.],
                [7,8],
                [9,10]])

In [ ]:
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [ ]:
t3.dtype

torch.float32

In [ ]:
# 3-Dimensional array
t4=torch.tensor([
    [[11,12,13],
    [13,14,15]],
    [[15,16,17],
    [17,18,19]]
])
t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])

In [ ]:
t4.shape

torch.Size([2, 2, 3])

In [ ]:
t4.size()

torch.Size([2, 2, 3])

#### Tensor Operations and Gradients

In [ ]:
# Create Tensors
x=torch.tensor(3.)
w=torch.tensor(4.,requires_grad=True) # We are alerting him that it can be used for differentiation
b=torch.tensor(5.,requires_grad=True) # We are alerting him that it can be used for differentiation

In [ ]:
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [ ]:
# Arithmetic Operations
y=w*x+b

In [ ]:
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
# Compute Derivatives
y.backward()  #Backward Propagation

In [ ]:
# Display gradients
print("dy/dx: ",x.grad)
print("dy/dw: ",w.grad)
print("dy/db: ",b.grad)

dy/dx:  None
dy/dw:  tensor(3.)
dy/db:  tensor(1.)


- Tensor Functions

In [ ]:
# Create a tensor with a fixed value for every element
t6=torch.full((3,2),42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [ ]:
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [ ]:
t7=torch.concat((t3,t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [ ]:
# compute the sin of each element
t8=torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [ ]:
t8.shape

torch.Size([6, 2])

In [ ]:
# Change the shape of a tensor
t9=t8.reshape(3,2,2)

In [ ]:
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

- Interoperability of PyTorch with Numpy

In [ ]:
import numpy as np

In [ ]:
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [ ]:
# Convert Numpy array to a PyTorch tensor
y=torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [ ]:
# Convert torch tensor to Numpy array
z=y.numpy()
z

array([[1, 2],
       [3, 4]])

### Linear Regression from Scratch using PyTorch

In [ ]:
# Making Training Data
# Input: (temperature,rainfall,humidity)
inputs=np.array([[73,67,43],
                [91,88,64],
                [87,134,58],
                [102,43,37],
                [69,96,70]],dtype='float32')

In [ ]:
inputs

array([[ 73.,  67.,  43.],
       [ 91.,  88.,  64.],
       [ 87., 134.,  58.],
       [102.,  43.,  37.],
       [ 69.,  96.,  70.]], dtype=float32)

In [ ]:
inputs.shape

(5, 3)

In [ ]:
# Targets (apples,oranges)

target=np.array([[56,70],
                [81,101],
                [119,133],
                [22,37],
                [103,119]],dtype='float32')

In [ ]:
target

array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]], dtype=float32)

In [ ]:
target.shape

(5, 2)

In [ ]:
# Convert Input and target to tensors
inputs=torch.from_numpy(inputs)
target=torch.from_numpy(target)

In [ ]:
# weights and biases
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)

In [ ]:
w,b

(tensor([[ 0.0875,  0.0629,  1.2892],
         [-0.2703, -0.8038, -0.1781]], requires_grad=True),
 tensor([1.2697, 0.3299], requires_grad=True))

In [ ]:
# Define the model

def model(x):
    return x @ w.t() + b

In [ ]:
# Prediction
preds=model(inputs)
print(preds)

tensor([[  67.3036,  -80.9133],
        [  97.2717, -106.3982],
        [  92.0802, -141.2233],
        [  60.5954,  -68.3914],
        [ 103.5858, -107.9512]], grad_fn=<AddBackward0>)


In [ ]:
# Actual
print(target)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
# Loss function MSE

def MSE(actual,pred):
    diff=actual-pred
    return torch.sum(diff*diff)/diff.numel()

In [ ]:
loss=MSE(target,preds)
print(loss)

tensor(20620.8633, grad_fn=<DivBackward0>)


In [ ]:
# Compute Gradients
loss.backward()

In [ ]:
print(w)
print(w.grad)

tensor([[ 0.0875,  0.0629,  1.2892],
        [-0.2703, -0.8038, -0.1781]], requires_grad=True)
tensor([[   788.2027,     59.5668,    287.0261],
        [-16031.3779, -18285.4609, -11090.7559]])


In [ ]:
print(b)
print(b.grad)

tensor([1.2697, 0.3299], requires_grad=True)
tensor([   7.9673, -192.9755])


In [ ]:
# adjust weight and reset grad
with torch.no_grad():
    w-=w.grad * 1e-5;
    b-=b.grad * 1e-5;
    w.grad.zero_()
    b.grad.zero_()

In [ ]:
print(w)
print(b)

tensor([[ 0.0796,  0.0623,  1.2863],
        [-0.1100, -0.6209, -0.0672]], requires_grad=True)
tensor([1.2697, 0.3318], requires_grad=True)


In [ ]:
# Calculate again
preds=model(inputs)
loss=MSE(target,preds)
print(loss)

tensor(14109.3877, grad_fn=<DivBackward0>)


In [ ]:
# Training for multiple epochs
for i in range(400):
    preds=model(inputs)
    loss=MSE(target,preds)
    loss.backward()
    with torch.no_grad():
        w-=w.grad * 1e-5; # Learning rate
        b-=b.grad * 1e-5;
        w.grad.zero_()
        b.grad.zero_()
    print(f"Epochs({i}/{100}) & Loss {loss}")    

Epochs(0/100) & Loss 14109.3876953125
Epochs(1/100) & Loss 9718.8251953125
Epochs(2/100) & Loss 6757.54296875
Epochs(3/100) & Loss 4759.4658203125
Epochs(4/100) & Loss 3410.510498046875
Epochs(5/100) & Loss 2499.019287109375
Epochs(6/100) & Loss 1882.3603515625
Epochs(7/100) & Loss 1464.4146728515625
Epochs(8/100) & Loss 1180.4085693359375
Epochs(9/100) & Loss 986.6923828125
Epochs(10/100) & Loss 853.8504028320312
Epochs(11/100) & Loss 762.0594482421875
Epochs(12/100) & Loss 697.9608764648438
Epochs(13/100) & Loss 652.5513916015625
Epochs(14/100) & Loss 619.7646484375
Epochs(15/100) & Loss 595.5110473632812
Epochs(16/100) & Loss 577.0350341796875
Epochs(17/100) & Loss 562.4791259765625
Epochs(18/100) & Loss 550.5914306640625
Epochs(19/100) & Loss 540.5276489257812
Epochs(20/100) & Loss 531.7188720703125
Epochs(21/100) & Loss 523.7811279296875
Epochs(22/100) & Loss 516.4554443359375
Epochs(23/100) & Loss 509.56695556640625
Epochs(24/100) & Loss 502.99755859375
Epochs(25/100) & Loss 496.

In [ ]:
preds=model(inputs)
loss=MSE(target,preds)
print(loss)

tensor(20.0840, grad_fn=<DivBackward0>)


In [ ]:
from math import sqrt
sqrt(loss)

4.481516920836422

In [ ]:
preds

tensor([[ 57.4887,  71.3125],
        [ 85.8857,  99.2043],
        [109.8102, 134.6802],
        [ 22.0818,  42.3053],
        [107.9858, 113.5668]], grad_fn=<AddBackward0>)

In [ ]:
target

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

- Therfore we can see that they are almost close each other

### Neural Network using PyTorch

In [ ]:
# To check GPU
!nvidia-smi

Wed Jul 10 17:46:40 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 546.26                 Driver Version: 546.26       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   43C    P8               4W /  50W |      0MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--