# Tensorflow Basics

In [1]:
import tensorflow as tf

In [2]:
print(f"Tensorflow Version: {tf.__version__}")

Tensorflow Version: 2.16.1


In [3]:
print(f"Keras Version: {tf.keras.__version__}")

Keras Version: 3.3.3


In [4]:
# Constant
gaurav=tf.constant(30)
gaurav

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [5]:
gaurav.numpy()

30

In [6]:
integer=tf.constant(20,dtype=tf.int64)
integer

<tf.Tensor: shape=(), dtype=int64, numpy=20>

In [7]:
array=tf.constant([[4,2],[8,6]])
print(array)

tf.Tensor(
[[4 2]
 [8 6]], shape=(2, 2), dtype=int32)


In [8]:
array.numpy()

array([[4, 2],
       [8, 6]])

- Commonly used method is to generate constant tf.ones and tf.zeros like of numpy np.ones and np.zeros.

In [9]:
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [10]:
print(tf.zeros(shape=(2,3)))

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [11]:
const1=tf.constant([[3,4,5],[3,4,5]])
const2=tf.constant([[1,2,3],[1,2,3]])
result=tf.add(const1,const2)
print(result)

tf.Tensor(
[[4 6 8]
 [4 6 8]], shape=(2, 3), dtype=int32)


- Random Constant

In [12]:
tf.random.normal(shape=(2,2),mean=0,stddev=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.9305707 , -0.03446743],
       [-0.20877956, -1.9359003 ]], dtype=float32)>

In [13]:
tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int64)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[7, 4],
       [2, 8]], dtype=int64)>

- Variables: A variable is a special tensor that is used to store variable values and needs to be initialized with some values

In [14]:
var1=tf.Variable(42)   # Rank 0 Tensor
var2=tf.Variable([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]]) # Rank 3 Tensor

In [15]:
var1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>

In [16]:
var2

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])>

In [17]:
# Re-Assigning a Variable
var=tf.Variable(89.)
var

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>

In [18]:
var.assign(74)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=74.0>

In [19]:
var

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=74.0>

In [20]:
initial_val=tf.random.normal(shape=(2,2))
a=tf.Variable(initial_val)

In [21]:
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.18312284,  1.1597252 ],
       [-1.6461045 , -0.29995006]], dtype=float32)>


In [22]:
new_value=tf.random.normal(shape=(2,2))
a.assign(new_value)
for i in range(2):
    for j in range(2):
        assert a[i,j]==new_value[i,j]

In [23]:
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.64115137, -0.8203098 ],
       [ 0.30543268,  0.7546119 ]], dtype=float32)>

In [24]:
new_value

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.64115137, -0.8203098 ],
       [ 0.30543268,  0.7546119 ]], dtype=float32)>

In [25]:
added_value=tf.random.normal(shape=(2,2))
a.assign_add(added_value)
for i in range(2):
    for j in range(2):
        assert a[i,j]==new_value[i,j]+added_value[i,j]

In [26]:
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 2.6738892 , -1.5791036 ],
       [ 0.686519  , -0.38407522]], dtype=float32)>

- Shaping a Tensor

In [27]:
tensor=tf.Variable([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
print(tensor.shape)

(2, 2, 3)


- Tensors can be reshaped and retain the same values, as is often required for constructing new values

In [28]:
tensor1=tf.reshape(tensor,[2,6])
tensor1

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])>

In [31]:
tensor2=tf.reshape(tensor,[1,12])
tensor2

<tf.Tensor: shape=(1, 12), dtype=int32, numpy=array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])>

#### Ranking (Dimensions) of a Tensor
- The rank of a tensor is the number of dimensions it has, that is the number of indices that are required to specify any particular element of that tensor.

In [35]:
tf.rank(tensor).numpy()

3

In [36]:
tf.rank(tensor1).numpy()

2

In [37]:
tf.rank(tensor2).numpy()

2

- Specifying an element of a tensor

In [40]:
tensor3=tensor[1,0,2]  # slice: 1, row:0, column: 2
tensor3

<tf.Tensor: shape=(), dtype=int32, numpy=8>

- Casting a Tensor to Numpy/Python Variable

In [42]:
print(tensor.numpy())

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [44]:
print(tensor[1,0,1].numpy())

7


In [46]:
# Finding the size of a Tensor
tensor_size=tf.size(input=tensor).numpy()
tensor_size

12

In [47]:
tensor.dtype

tf.int32

- Tensorflow Mathematical Operations

In [49]:
a=tf.random.normal(shape=(2,2))
b=tf.random.normal(shape=(2,2))
c=a+b
d=tf.square(c)
e=tf.exp(c)

In [50]:
print(a)

tf.Tensor(
[[ 1.185691   -0.81120604]
 [ 0.9649526  -0.15820879]], shape=(2, 2), dtype=float32)


In [51]:
print(b)

tf.Tensor(
[[-0.21164237  0.64855134]
 [-0.19320673 -0.5046417 ]], shape=(2, 2), dtype=float32)


In [52]:
print(c)

tf.Tensor(
[[ 0.9740486  -0.1626547 ]
 [ 0.77174586 -0.6628505 ]], shape=(2, 2), dtype=float32)


In [53]:
print(d)

tf.Tensor(
[[0.9487707  0.02645655]
 [0.59559166 0.43937078]], shape=(2, 2), dtype=float32)


In [54]:
print(e)

tf.Tensor(
[[2.648646   0.8498846 ]
 [2.1635401  0.51538014]], shape=(2, 2), dtype=float32)


- Perform element-wise Primitive tensor Operations

In [55]:
tensor*tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[  0,   1,   4],
        [  9,  16,  25]],

       [[ 36,  49,  64],
        [ 81, 100, 121]]])>

#### Broadcasting:
    - Element-wise tensor operations support broadcasting in the same way that numpy arrays do.
    - The simplest example is that of multiplying a tensor by a scaler

In [56]:
tensor4=tensor*4
print(tensor4)

tf.Tensor(
[[[ 0  4  8]
  [12 16 20]]

 [[24 28 32]
  [36 40 44]]], shape=(2, 2, 3), dtype=int32)


- Transpose matrix Multiplication

In [58]:
matrix_u=tf.constant([[3,4,3]])
matrix_v=tf.constant([[1,2,1]])
tf.matmul(matrix_u,tf.transpose(matrix_v)).numpy()

array([[14]])

- Casting a Tensor to another (tensor) Datatype

In [59]:
tensor1

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])>

In [60]:
i=tf.cast(tensor1,dtype=tf.int64)
print(i)

tf.Tensor(
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]], shape=(2, 6), dtype=int64)


- Casting with Truncation

In [61]:
j=tf.cast(tf.constant(4.9),dtype=tf.int64)

In [62]:
j

<tf.Tensor: shape=(), dtype=int64, numpy=4>

### Declaring Ragged Tensors
    - A ragged tensor is a tensor with one or more ragged dimensions. Ragged dimensions are dimensions that have alices that may have different lengths. There are a variety of methods for declaring ragged arrays, the simplest being a constant ragged array.

In [64]:
ragged=tf.ragged.constant([[5,2,6,1],[],[4,10,7],[8],[6,7]])

In [65]:
print(ragged)

<tf.RaggedTensor [[5, 2, 6, 1], [], [4, 10, 7], [8], [6, 7]]>


In [66]:
print(ragged[0:])

<tf.RaggedTensor [[5, 2, 6, 1], [], [4, 10, 7], [8], [6, 7]]>


In [67]:
print(ragged[1:])

<tf.RaggedTensor [[], [4, 10, 7], [8], [6, 7]]>


In [68]:
print(ragged[2:])

<tf.RaggedTensor [[4, 10, 7], [8], [6, 7]]>


In [69]:
print(ragged[3:])

<tf.RaggedTensor [[8], [6, 7]]>


In [70]:
print(ragged[4:])

<tf.RaggedTensor [[6, 7]]>


- Finding the Squared difference between 2 Sensors

In [71]:
varx = [1,3,5,7,11]
vary = 5
varz = tf.math.squared_difference(varx,vary)
varz

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  4,  0,  4, 36])>

- [(1-5)^2,(3-5)^2,(5-5)^2,(7-5)^2,(11-5)^2] ==>[16,4,0,4,36]

In [72]:
number=tf.constant([[4,5],[7,3]])

In [75]:
tf.reduce_mean(input_tensor=number).numpy()

4

In [76]:
tf.reduce_mean(input_tensor=number,axis=0).numpy()

array([5, 4])

In [77]:
tf.reduce_mean(input_tensor=number,axis=0,keepdims=True)

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[5, 4]])>

In [78]:
ran=tf.random.normal(shape=(3,2),mean=10,stddev=2,dtype=tf.float32,seed=None,name=None)

In [79]:
print(ran)

tf.Tensor(
[[11.618146 11.352605]
 [ 9.948454  8.310796]
 [ 9.577534  8.668596]], shape=(3, 2), dtype=float32)


In [81]:
ran2=tf.random.uniform(shape=(2,4),minval=0,maxval=None,dtype=tf.float32,seed=None,name=None)

In [82]:
print(ran2)

tf.Tensor(
[[0.14453197 0.3103932  0.65346575 0.63053226]
 [0.877      0.83857715 0.0631721  0.85094273]], shape=(2, 4), dtype=float32)


#### Setting the Seed

In [95]:
tf.random.set_seed(11)
rand1=tf.random.uniform(shape=(2,2),maxval=10,dtype=tf.int64)
rand2=tf.random.uniform(shape=(2,2),maxval=10,dtype=tf.int64)
print(rand1)
print(rand2)

tf.Tensor(
[[0 7]
 [6 6]], shape=(2, 2), dtype=int64)
tf.Tensor(
[[1 3]
 [6 9]], shape=(2, 2), dtype=int64)


### Practical Example of Random values using Dices

In [96]:
dice1=tf.Variable(tf.random.uniform([10,1],minval=1, maxval=7, dtype=tf.int64))
dice2=tf.Variable(tf.random.uniform([10,1],minval=1, maxval=7, dtype=tf.int64))
dice_sum=dice1+dice2
resulting_matrix=tf.concat(values=[dice1,dice2,dice_sum],axis=1)
print(resulting_matrix)

tf.Tensor(
[[5 1 6]
 [1 5 6]
 [1 4 5]
 [1 1 2]
 [1 5 6]
 [1 2 3]
 [6 3 9]
 [6 2 8]
 [1 3 4]
 [6 3 9]], shape=(10, 3), dtype=int64)


In [97]:
# 1D Tensor
t5=tf.constant([2,11,5,42,7,19,-6,-11,29])
print(t5)

tf.Tensor([  2  11   5  42   7  19  -6 -11  29], shape=(9,), dtype=int32)


In [98]:
i=tf.argmax(input=t5)
print("Index of max: ",i)
print("Max Element: ",t5[i].numpy())

Index of max:  tf.Tensor(3, shape=(), dtype=int64)
Max Element:  42


In [101]:
j=tf.argmin(input=t5)
print("Index of max: ",j)
print("Max Element: ",t5[j].numpy())

Index of max:  tf.Tensor(7, shape=(), dtype=int64)
Max Element:  -11


In [102]:
t6=tf.reshape(t5,[3,3])
print(t6)

tf.Tensor(
[[  2  11   5]
 [ 42   7  19]
 [ -6 -11  29]], shape=(3, 3), dtype=int32)


In [105]:
i=tf.argmax(input=t6,axis=0)
print("Index of max: ",i)

Index of max:  tf.Tensor([1 0 2], shape=(3,), dtype=int64)


In [107]:
i=tf.argmin(input=t6,axis=0)
print("Index of max: ",i)

Index of max:  tf.Tensor([2 2 0], shape=(3,), dtype=int64)


In [108]:
i=tf.argmax(input=t6,axis=1)
print("Index of max: ",i)

Index of max:  tf.Tensor([1 0 2], shape=(3,), dtype=int64)


In [109]:
i=tf.argmin(input=t6,axis=1)
print("Index of max: ",i)

Index of max:  tf.Tensor([0 1 1], shape=(3,), dtype=int64)


- Saving and restoring Tensor values using Checkpoint

In [110]:
variable=tf.Variable([[1,3,5,7],[11,13,17,19]])
checkpoint=tf.train.Checkpoint(var=variable)
save_path=checkpoint.save('./vars')

In [111]:
variable.assign([[0,0,0,0],[0,0,0,0]])
print(variable)
checkpoint.restore(save_path)
print(variable)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0]])>
<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 1,  3,  5,  7],
       [11, 13, 17, 19]])>


#### Using tf.function()

    1. tf.function is a function that will take a Python function and return a Tensorflow graph.
    2. The Advantage of this is that graphs can apply Optimization and exploit parallelism in the Python function.
    3. tf.function is new to tensorflow 2

In [112]:
def f1(x,y):
    return tf.reduce_mean(input_tensor=tf.multiply(x**2,5) + y**2)

In [113]:
f2=tf.function(f1)
x=tf.constant([4.,-5.])
y=tf.constant([2.,3.])

# f1 and f2 returns the same value but f2 executes as a Tensorflow graph
assert f1(x,y).numpy() == f2(x,y).numpy()

In [115]:
f2(x,y).numpy()

109.0

### Calculate the Gradient

1. Gradient tape:
    - Another difference from numpy is that it can automatically track the gradient of any variable.
    - Open one GradientTape and tape.watch() track varuables through

In [116]:
a=tf.random.normal(shape=(2,2))
b=tf.random.normal(shape=(2,2))

In [118]:
with tf.GradientTape() as tape:
    tape.watch(a)
    c=tf.sqrt(tf.square(a)+tf.square(b))
    dc_da=tape.gradient(c,a) # Differentiation of c wrt a
    print(dc_da)

tf.Tensor(
[[-0.469929    0.89920384]
 [-0.66446567 -0.79767007]], shape=(2, 2), dtype=float32)


In [119]:
a=tf.Variable(a)
with tf.GradientTape() as tape:
    c=tf.sqrt(tf.square(a)+tf.square(b))
    dc_da=tape.gradient(c,a) # Differentiation of c wrt a
    print(dc_da)

tf.Tensor(
[[-0.469929    0.89920384]
 [-0.66446567 -0.79767007]], shape=(2, 2), dtype=float32)


- Higher Order Derivative

In [121]:
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as tape:
        c=tf.sqrt(tf.square(a)+tf.square(b))
        dc_da=tape.gradient(c,a)
    d2c_d2a=outer_tape.gradient(c,a)
    print(d2c_d2a)

tf.Tensor(
[[-0.469929    0.89920384]
 [-0.66446567 -0.79767007]], shape=(2, 2), dtype=float32)
