# Tensorflow Basics

In [1]:
import tensorflow as tf

In [2]:
print(f"Tensorflow Version: {tf.__version__}")

Tensorflow Version: 2.16.1


In [3]:
print(f"Keras Version: {tf.keras.__version__}")

Keras Version: 3.3.3


In [4]:
# Constant
gaurav=tf.constant(30)
gaurav

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [5]:
gaurav.numpy()

30

In [6]:
integer=tf.constant(20,dtype=tf.int64)
integer

<tf.Tensor: shape=(), dtype=int64, numpy=20>

In [7]:
array=tf.constant([[4,2],[8,6]])
print(array)

tf.Tensor(
[[4 2]
 [8 6]], shape=(2, 2), dtype=int32)


In [8]:
array.numpy()

array([[4, 2],
       [8, 6]])

- Commonly used method is to generate constant tf.ones and tf.zeros like of numpy np.ones and np.zeros.

In [10]:
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [11]:
print(tf.zeros(shape=(2,3)))

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [12]:
const1=tf.constant([[3,4,5],[3,4,5]])
const2=tf.constant([[1,2,3],[1,2,3]])
result=tf.add(const1,const2)
print(result)

tf.Tensor(
[[4 6 8]
 [4 6 8]], shape=(2, 3), dtype=int32)
