# Naive Baye's Machine Learning Algorithm

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
from sklearn.datasets import load_iris

In [3]:
X,y=load_iris(return_X_y=True)

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [6]:
from sklearn.naive_bayes import GaussianNB

In [7]:
gnb=GaussianNB()

In [8]:
gnb.fit(X_train,y_train)

GaussianNB()

In [9]:
y_pred=gnb.predict(X_test)

In [10]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [11]:
# Accuracy Score
print(accuracy_score(y_test,y_pred))

1.0


In [12]:
# Classification Report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [13]:
# Confusion Matrix
print(confusion_matrix(y_test,y_pred))

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]


### Naive Bayes Classification on tips Datatset

In [14]:
df2=sns.load_dataset('tips')

In [15]:
df2.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [16]:
df2.drop(columns=['size'],inplace=True)

In [17]:
df2.head()

total_bill   tip     sex smoker  day    time
0       16.99  1.01  Female     No  Sun  Dinner
1       10.34  1.66    Male     No  Sun  Dinner
2       21.01  3.50    Male     No  Sun  Dinner
3       23.68  3.31    Male     No  Sun  Dinner
4       24.59  3.61  Female     No  Sun  Dinner

In [18]:
df2['sex'].unique()

['Female', 'Male']
Categories (2, object): ['Male', 'Female']

In [19]:
df2['sex']=df2['sex'].map({'Female':0,'Male':1})

In [20]:
df2.head()

total_bill   tip sex smoker  day    time
0       16.99  1.01   0     No  Sun  Dinner
1       10.34  1.66   1     No  Sun  Dinner
2       21.01  3.50   1     No  Sun  Dinner
3       23.68  3.31   1     No  Sun  Dinner
4       24.59  3.61   0     No  Sun  Dinner

In [21]:
df2['smoker'].unique()

['No', 'Yes']
Categories (2, object): ['Yes', 'No']

In [22]:
df2['smoker']=df2['smoker'].map({'Yes':1,'No':0})

In [23]:
df2.head()

total_bill   tip sex smoker  day    time
0       16.99  1.01   0      0  Sun  Dinner
1       10.34  1.66   1      0  Sun  Dinner
2       21.01  3.50   1      0  Sun  Dinner
3       23.68  3.31   1      0  Sun  Dinner
4       24.59  3.61   0      0  Sun  Dinner

In [24]:
df2['day'].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [25]:
# df2['day']=df2['day'].map({'Sun':4,'Sat':3,'Fri':2,'Thur':1})

In [26]:
from sklearn.preprocessing import OneHotEncoder

In [27]:
ohe=OneHotEncoder()

In [28]:
day=ohe.fit_transform(df2[['day']]).toarray()

In [29]:
day

array([[0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],


In [30]:
day_df=pd.DataFrame(day,columns=ohe.get_feature_names_out())

In [31]:
day_df

day_Fri  day_Sat  day_Sun  day_Thur
0        0.0      0.0      1.0       0.0
1        0.0      0.0      1.0       0.0
2        0.0      0.0      1.0       0.0
3        0.0      0.0      1.0       0.0
4        0.0      0.0      1.0       0.0
..       ...      ...      ...       ...
239      0.0      1.0      0.0       0.0
240      0.0      1.0      0.0       0.0
241      0.0      1.0      0.0       0.0
242      0.0      1.0      0.0       0.0
243      0.0      0.0      0.0       1.0

[244 rows x 4 columns]

In [32]:
df2=pd.concat([df2,day_df],axis=1)

In [33]:
df2

total_bill   tip sex smoker   day    time  day_Fri  day_Sat  day_Sun   
0         16.99  1.01   0      0   Sun  Dinner      0.0      0.0      1.0  \
1         10.34  1.66   1      0   Sun  Dinner      0.0      0.0      1.0   
2         21.01  3.50   1      0   Sun  Dinner      0.0      0.0      1.0   
3         23.68  3.31   1      0   Sun  Dinner      0.0      0.0      1.0   
4         24.59  3.61   0      0   Sun  Dinner      0.0      0.0      1.0   
..          ...   ...  ..    ...   ...     ...      ...      ...      ...   
239       29.03  5.92   1      0   Sat  Dinner      0.0      1.0      0.0   
240       27.18  2.00   0      1   Sat  Dinner      0.0      1.0      0.0   
241       22.67  2.00   1      1   Sat  Dinner      0.0      1.0      0.0   
242       17.82  1.75   1      0   Sat  Dinner      0.0      1.0      0.0   
243       18.78  3.00   0      0  Thur  Dinner      0.0      0.0      0.0   

     day_Thur  
0         0.0  
1         0.0  
2         0.0  
3         0.0  
4         0.0  
..        ...  
239       0.0  
240       0.0  
241       0.0  
242       0.0  
243       1.0  

[244 rows x 10 columns]

In [34]:
df2.drop(columns=['day'],inplace=True)

In [35]:
df2.head()

total_bill   tip sex smoker    time  day_Fri  day_Sat  day_Sun  day_Thur
0       16.99  1.01   0      0  Dinner      0.0      0.0      1.0       0.0
1       10.34  1.66   1      0  Dinner      0.0      0.0      1.0       0.0
2       21.01  3.50   1      0  Dinner      0.0      0.0      1.0       0.0
3       23.68  3.31   1      0  Dinner      0.0      0.0      1.0       0.0
4       24.59  3.61   0      0  Dinner      0.0      0.0      1.0       0.0

In [36]:
df2['time'].unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [37]:
df2['time']=df2['time'].map({'Dinner':1,'Lunch':0})

In [38]:
df2.head()

total_bill   tip sex smoker time  day_Fri  day_Sat  day_Sun  day_Thur
0       16.99  1.01   0      0    1      0.0      0.0      1.0       0.0
1       10.34  1.66   1      0    1      0.0      0.0      1.0       0.0
2       21.01  3.50   1      0    1      0.0      0.0      1.0       0.0
3       23.68  3.31   1      0    1      0.0      0.0      1.0       0.0
4       24.59  3.61   0      0    1      0.0      0.0      1.0       0.0

In [39]:
#Independent and Dependent Features
X1=df2.drop(columns=['time'])
y1=df2['time']

In [40]:
X1_train,X1_test,y1_train,y1_test=train_test_split(X1,y1,test_size=0.3,random_state=0)

In [41]:
gnb2=GaussianNB()

In [42]:
gnb2.fit(X1_train,y1_train)

GaussianNB()

In [43]:
y_pred2=gnb2.predict(X1_test)

In [44]:
# Accuracy Score
print(accuracy_score(y1_test,y_pred2))

0.918918918918919
