## Numpy: 1

In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5]

In [3]:
l

[1, 2, 3, 4, 5]

In [4]:
arr=np.array(l)

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [7]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [8]:
arr2=np.array([[1,2,3],[4,5,6]])

In [9]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr2[0][0]

1

In [11]:
arr2[0][1]

2

In [12]:
arr2[0][2]

3

In [13]:
arr2[1][0]

4

In [14]:
arr2[1][1]

5

In [15]:
arr2[1][2]

6

In [16]:
arr2.ndim

2

In [17]:
arr.ndim

1

In [18]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.matrix(arr2)

matrix([[1, 2, 3],
        [4, 5, 6]])

In [22]:
mat=np.matrix(l)

In [21]:
np.matrix(l).ndim

2

In [23]:
mat

matrix([[1, 2, 3, 4, 5]])

In [24]:
l

[1, 2, 3, 4, 5]

In [25]:
a=l

In [26]:
a

[1, 2, 3, 4, 5]

In [27]:
a[0]=100

In [28]:
a

[100, 2, 3, 4, 5]

In [29]:
l

[100, 2, 3, 4, 5]

In [30]:
b=np.copy(l)

In [31]:
b

array([100,   2,   3,   4,   5])

In [32]:
b[0]=240

In [33]:
b

array([240,   2,   3,   4,   5])

In [34]:
a

[100, 2, 3, 4, 5]

In [35]:
l

[100, 2, 3, 4, 5]

In [36]:
np.fromfunction(lambda i,j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [37]:
np.fromfunction(lambda i,j : i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [41]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [42]:
iterable = (i*i for i in range(5))

In [43]:
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

In [44]:
np.fromstring('23 45 56' , sep = ' ')

array([23., 45., 56.])

In [45]:
np.fromstring('23,45,56' , sep = ',')

array([23., 45., 56.])

In [46]:
l

[100, 2, 3, 4, 5]

In [47]:
arr

array([1, 2, 3, 4, 5])

In [48]:
arr[0]=256

In [49]:
arr

array([256,   2,   3,   4,   5])

In [50]:
arr.ndim

1

In [52]:
arr.size

5

In [53]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
arr2.size

6

In [55]:
arr.shape

(5,)

In [56]:
arr2.shape

(2, 3)

In [57]:
arr2.dtype

dtype('int32')

In [58]:
arr.dtype

dtype('int32')