## Numpy: 2

In [1]:
import numpy as np

In [2]:
range(5)

range(0, 5)

In [3]:
list(range(5))

[0, 1, 2, 3, 4]

In [4]:
list(range(0,5,2))

[0, 2, 4]

In [5]:
list(range(0.4,5.4))

TypeError: 'float' object cannot be interpreted as an integer

In [8]:
np.arange(0.4,5.4)

array([0.4, 1.4, 2.4, 3.4, 4.4])

In [9]:
np.arange(0.4,5.4,0.2)

array([0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8,
       3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2])

In [10]:
list(np.arange(0.4,5.4,0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002]

In [13]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [15]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
arr=np.ones((3,4))

In [23]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [25]:
arr + 4

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [26]:
np.empty((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
arr2=np.eye(4)

In [31]:
arr2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
import pandas as pd

In [33]:
pd.DataFrame(arr2)

0    1    2    3
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0

In [34]:
np.random.rand(2,3)

array([[0.08939333, 0.5348997 , 0.68124278],
       [0.74265903, 0.35953218, 0.28396598]])

In [36]:
np.random.randn(2,3)

array([[-0.47528475,  2.29839541, -1.44088361],
       [ 0.07328428, -1.17855175, -0.36926036]])

In [42]:
arr3=np.random.randint(1,5,(3,4))

In [43]:
arr3

array([[2, 4, 3, 4],
       [4, 1, 1, 3],
       [1, 2, 1, 3]])

In [44]:
arr3.size

12

In [46]:
arr3.shape

(3, 4)

In [48]:
arr3.reshape(6,2)

array([[2, 4],
       [3, 4],
       [4, 1],
       [1, 3],
       [1, 2],
       [1, 3]])

In [49]:
arr3.reshape(2,2,3)

array([[[2, 4, 3],
        [4, 4, 1]],

       [[1, 3, 1],
        [2, 1, 3]]])

In [50]:
arr3=np.random.randint(1,10,(5,6))

In [51]:
arr3

array([[4, 7, 8, 3, 1, 4],
       [4, 6, 9, 4, 2, 7],
       [5, 3, 1, 5, 7, 8],
       [5, 6, 8, 4, 9, 4],
       [2, 6, 6, 2, 2, 1]])

In [52]:
arr3 > 8

array([[False, False, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False,  True, False],
       [False, False, False, False, False, False]])

In [55]:
arr3[arr3>8]

array([9, 9])

In [56]:
arr3[0][0]

4

In [57]:
arr3[0]

array([4, 7, 8, 3, 1, 4])

In [59]:
arr3[0,[0,1]]

array([4, 7])

In [64]:
sample=arr3[2:4,[2,3]]

In [65]:
sample

array([[1, 5],
       [8, 4]])

In [66]:
sample.ndim

2

In [67]:
arr4=np.random.randint(1,3,(3,3))
arr5=np.random.randint(1,3,(3,3))

In [68]:
arr4

array([[2, 2, 2],
       [1, 2, 2],
       [1, 1, 2]])

In [69]:
arr5

array([[1, 2, 1],
       [1, 1, 2],
       [1, 1, 2]])

In [70]:
arr4 + arr5

array([[3, 4, 3],
       [2, 3, 4],
       [2, 2, 4]])

In [72]:
arr4 - arr5

array([[1, 0, 1],
       [0, 1, 0],
       [0, 0, 0]])

In [73]:
arr4 * arr5

array([[2, 4, 2],
       [1, 2, 4],
       [1, 1, 4]])

In [74]:
#matrix multiplication
arr4@arr5

array([[ 6,  8, 10],
       [ 5,  6,  9],
       [ 4,  5,  7]])

In [75]:
arr3/0

C:\Users\admin\AppData\Local\Temp\ipykernel_14156\1466893960.py:1: RuntimeWarning: divide by zero encountered in divide
  arr3/0


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

#### Numpy Broadcasting

In [76]:
arr6=np.zeros((3,4))

In [77]:
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [79]:
arr6 + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [80]:
arr7=np.array([1,2,3,4])

In [81]:
arr7 + arr6

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [82]:
arr7

array([1, 2, 3, 4])

In [83]:
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
arr8=np.array([[3,4,5]])

In [85]:
arr8

array([[3, 4, 5]])

In [88]:
array=arr6+arr8.T

In [87]:
arr8.T

array([[3],
       [4],
       [5]])

In [89]:
array

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [90]:
np.sqrt(array)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [91]:
np.log10(array)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [92]:
np.exp(array)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [93]:
np.max(array)

5.0

In [94]:
np.min(array)

3.0