## Numpy:3

In [1]:
import numpy as np

#### Numpy - Array Manipulation

In [4]:
arr=np.random.randint(1,10,(4,4))

In [5]:
arr

array([[8, 4, 5, 3],
       [7, 3, 1, 4],
       [3, 2, 4, 8],
       [3, 1, 3, 7]])

In [6]:
arr.reshape(8,2)

array([[8, 4],
       [5, 3],
       [7, 3],
       [1, 4],
       [3, 2],
       [4, 8],
       [3, 1],
       [3, 7]])

In [7]:
arr

array([[8, 4, 5, 3],
       [7, 3, 1, 4],
       [3, 2, 4, 8],
       [3, 1, 3, 7]])

In [9]:
#Transpose
arr.T

array([[8, 7, 3, 3],
       [4, 3, 2, 1],
       [5, 1, 4, 3],
       [3, 4, 8, 7]])

In [10]:
arr.flatten()

array([8, 4, 5, 3, 7, 3, 1, 4, 3, 2, 4, 8, 3, 1, 3, 7])

In [11]:
np.expand_dims(arr,axis=1)

array([[[8, 4, 5, 3]],

       [[7, 3, 1, 4]],

       [[3, 2, 4, 8]],

       [[3, 1, 3, 7]]])

In [13]:
np.expand_dims(arr,axis=0)

array([[[8, 4, 5, 3],
        [7, 3, 1, 4],
        [3, 2, 4, 8],
        [3, 1, 3, 7]]])

In [15]:
data = np.array([[1],[2],[3]])

In [19]:
np.squeeze(data)

array([1, 2, 3])

In [20]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [28]:
np.roll(data,3)

array([[1],
       [2],
       [3]])

In [30]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### Numpy: Binary Operators

In [31]:
arr2=np.random.randint(1,10,(3,4))

In [32]:
arr2

array([[5, 7, 7, 9],
       [5, 1, 2, 2],
       [1, 6, 3, 3]])

In [33]:
arr3=np.random.randint(1,10,(3,4))

In [34]:
arr3

array([[1, 1, 4, 4],
       [2, 3, 4, 8],
       [5, 8, 5, 2]])

In [36]:
arr2+arr3

array([[ 6,  8, 11, 13],
       [ 7,  4,  6, 10],
       [ 6, 14,  8,  5]])

In [37]:
arr2-arr3

array([[ 4,  6,  3,  5],
       [ 3, -2, -2, -6],
       [-4, -2, -2,  1]])

In [40]:
arr3

array([[1, 1, 4, 4],
       [2, 3, 4, 8],
       [5, 8, 5, 2]])

In [41]:
arr2

array([[5, 7, 7, 9],
       [5, 1, 2, 2],
       [1, 6, 3, 3]])

In [43]:
arr2>arr3

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False,  True]])

In [44]:
~arr2

array([[ -6,  -8,  -8, -10],
       [ -6,  -2,  -3,  -3],
       [ -2,  -7,  -4,  -4]])

#### Numpy: String Functions

In [45]:
arr4=np.array(["Gaurav","Bhadane"])

In [46]:
arr4

array(['Gaurav', 'Bhadane'], dtype='<U7')

In [47]:
np.char.upper(arr4)

array(['GAURAV', 'BHADANE'], dtype='<U7')

In [48]:
np.char.capitalize(arr4)

array(['Gaurav', 'Bhadane'], dtype='<U7')

In [49]:
np.char.title(arr4)

array(['Gaurav', 'Bhadane'], dtype='<U7')

#### Numpy: Mathematical Functions

In [50]:
arr

array([[8, 4, 5, 3],
       [7, 3, 1, 4],
       [3, 2, 4, 8],
       [3, 1, 3, 7]])

In [51]:
np.sin(arr)

array([[ 0.98935825, -0.7568025 , -0.95892427,  0.14112001],
       [ 0.6569866 ,  0.14112001,  0.84147098, -0.7568025 ],
       [ 0.14112001,  0.90929743, -0.7568025 ,  0.98935825],
       [ 0.14112001,  0.84147098,  0.14112001,  0.6569866 ]])

In [52]:
np.cos(arr)

array([[-0.14550003, -0.65364362,  0.28366219, -0.9899925 ],
       [ 0.75390225, -0.9899925 ,  0.54030231, -0.65364362],
       [-0.9899925 , -0.41614684, -0.65364362, -0.14550003],
       [-0.9899925 ,  0.54030231, -0.9899925 ,  0.75390225]])

In [53]:
np.tan(arr)

array([[-6.79971146,  1.15782128, -3.38051501, -0.14254654],
       [ 0.87144798, -0.14254654,  1.55740772,  1.15782128],
       [-0.14254654, -2.18503986,  1.15782128, -6.79971146],
       [-0.14254654,  1.55740772, -0.14254654,  0.87144798]])

In [55]:
np.log10(arr)

array([[0.90308999, 0.60205999, 0.69897   , 0.47712125],
       [0.84509804, 0.47712125, 0.        , 0.60205999],
       [0.47712125, 0.30103   , 0.60205999, 0.90308999],
       [0.47712125, 0.        , 0.47712125, 0.84509804]])

In [56]:
np.exp(arr)

array([[2.98095799e+03, 5.45981500e+01, 1.48413159e+02, 2.00855369e+01],
       [1.09663316e+03, 2.00855369e+01, 2.71828183e+00, 5.45981500e+01],
       [2.00855369e+01, 7.38905610e+00, 5.45981500e+01, 2.98095799e+03],
       [2.00855369e+01, 2.71828183e+00, 2.00855369e+01, 1.09663316e+03]])

In [58]:
np.power(arr,2)

array([[64, 16, 25,  9],
       [49,  9,  1, 16],
       [ 9,  4, 16, 64],
       [ 9,  1,  9, 49]], dtype=int32)

In [59]:
np.mean(arr)

4.125

In [60]:
np.median(arr)

3.5

In [62]:
np.std(arr)

2.2043990110685496

In [63]:
np.var(arr)

4.859375

In [64]:
np.min(arr)

1

In [65]:
np.max(arr)

8

#### Numpy: Aithmetic Operations

In [66]:
arr2

array([[5, 7, 7, 9],
       [5, 1, 2, 2],
       [1, 6, 3, 3]])

In [67]:
arr3

array([[1, 1, 4, 4],
       [2, 3, 4, 8],
       [5, 8, 5, 2]])

In [68]:
arr2-arr3

array([[ 4,  6,  3,  5],
       [ 3, -2, -2, -6],
       [-4, -2, -2,  1]])

In [69]:
np.subtract(arr2,arr3)

array([[ 4,  6,  3,  5],
       [ 3, -2, -2, -6],
       [-4, -2, -2,  1]])

In [70]:
np.add(arr2,arr3)

array([[ 6,  8, 11, 13],
       [ 7,  4,  6, 10],
       [ 6, 14,  8,  5]])

In [71]:
np.multiply(arr2,arr3)

array([[ 5,  7, 28, 36],
       [10,  3,  8, 16],
       [ 5, 48, 15,  6]])

In [72]:
np.mod(arr2,arr3)

array([[0, 0, 3, 1],
       [1, 1, 2, 2],
       [1, 6, 3, 1]])

In [73]:
np.power(arr2,arr3)

array([[      5,       7,    2401,    6561],
       [     25,       1,      16,     256],
       [      1, 1679616,     243,       9]])

In [74]:
np.sqrt(arr2)

array([[2.23606798, 2.64575131, 2.64575131, 3.        ],
       [2.23606798, 1.        , 1.41421356, 1.41421356],
       [1.        , 2.44948974, 1.73205081, 1.73205081]])

#### Numpy: Statistical Functions

In [76]:
np.mean(arr2)

4.25

In [77]:
np.median(arr2)

4.0

In [78]:
np.var(arr2)

6.354166666666667

In [79]:
np.std(arr2)

2.520747243709029