## Numpy: 4

#### Sort, Search & Counting functions

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,8,5,34,14,7,16,30])

In [3]:
np.sort(arr)

array([ 1,  2,  5,  7,  8, 14, 16, 30, 34])

In [6]:
np.searchsorted(arr,7)

2

In [7]:
arr2=np.array([56,25,0,0,4,5,0,4,0,0,0,0,4,0,5,5,0,0,6,6,0,7,0])

In [8]:
arr2

array([56, 25,  0,  0,  4,  5,  0,  4,  0,  0,  0,  0,  4,  0,  5,  5,  0,
        0,  6,  6,  0,  7,  0])

In [9]:
np.count_nonzero(arr2)

11

In [11]:
np.where(arr>7)

(array([2, 4, 5, 7, 8], dtype=int64),)

In [12]:
np.extract(arr>2,arr)

array([ 8,  5, 34, 14,  7, 16, 30])

#### Numpy: Byte Swapping

In [13]:
arr

array([ 1,  2,  8,  5, 34, 14,  7, 16, 30])

In [16]:
arr.byteswap()  #Storage ids/locations

array([ 16777216,  33554432, 134217728,  83886080, 570425344, 234881024,
       117440512, 268435456, 503316480])

In [17]:
arr.byteswap(True)

array([ 16777216,  33554432, 134217728,  83886080, 570425344, 234881024,
       117440512, 268435456, 503316480])

In [18]:
arr

array([ 16777216,  33554432, 134217728,  83886080, 570425344, 234881024,
       117440512, 268435456, 503316480])

#### Numpy: Copies & Views

In [25]:
arr2=np.array([2,5,66,5,4,5,2,48,2,5,8,0,5,45,2])

In [26]:
arr2

array([ 2,  5, 66,  5,  4,  5,  2, 48,  2,  5,  8,  0,  5, 45,  2])

In [27]:
a=np.copy(arr2)

In [28]:
a

array([ 2,  5, 66,  5,  4,  5,  2, 48,  2,  5,  8,  0,  5, 45,  2])

In [29]:
a+10

array([12, 15, 76, 15, 14, 15, 12, 58, 12, 15, 18, 10, 15, 55, 12])

In [30]:
a

array([ 2,  5, 66,  5,  4,  5,  2, 48,  2,  5,  8,  0,  5, 45,  2])

In [36]:
b=arr2.view()  #Swallow Copy

In [32]:
b

array([ 2,  5, 66,  5,  4,  5,  2, 48,  2,  5,  8,  0,  5, 45,  2])

In [33]:
b[0]=1000

In [34]:
b

array([1000,    5,   66,    5,    4,    5,    2,   48,    2,    5,    8,
          0,    5,   45,    2])

In [35]:
arr2

array([1000,    5,   66,    5,    4,    5,    2,   48,    2,    5,    8,
          0,    5,   45,    2])

#### Numpy: Matrix Library

In [37]:
import numpy.matlib as nm

In [38]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [39]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

#### Numpy: Linear Algebra

In [41]:
arr2

array([1000,    5,   66,    5,    4,    5,    2,   48,    2,    5,    8,
          0,    5,   45,    2])

In [45]:
arr3=np.array([10,25,1,0,15,4,2,6,2,45,8,96,45,1,4])

In [46]:
arr3

array([10, 25,  1,  0, 15,  4,  2,  6,  2, 45,  8, 96, 45,  1,  4])

In [47]:
np.dot(arr2,arr3)

11134