# PCA Implementation with Python

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
from sklearn.decomposition import PCA

In [3]:
from sklearn.datasets import load_iris

In [4]:
dataset=load_iris()

In [5]:
X=dataset['data']
y=dataset['target']

In [6]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [10]:
X_train

array([[5.5, 2.4, 3.7, 1. ],
       [6.3, 2.8, 5.1, 1.5],
       [6.4, 3.1, 5.5, 1.8],
       [6.6, 3. , 4.4, 1.4],
       [7.2, 3.6, 6.1, 2.5],
       [5.7, 2.9, 4.2, 1.3],
       [7.6, 3. , 6.6, 2.1],
       [5.6, 3. , 4.5, 1.5],
       [5.1, 3.5, 1.4, 0.2],
       [7.7, 2.8, 6.7, 2. ],
       [5.8, 2.7, 4.1, 1. ],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 2. , 3.5, 1. ],
       [6.3, 2.7, 4.9, 1.8],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 2.7, 4.2, 1.3],
       [5.1, 3.4, 1.5, 0.2],
       [5.7, 3. , 4.2, 1.2],
       [7.7, 3.8, 6.7, 2.2],
       [4.6, 3.2, 1.4, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.5, 5. , 2. ],
       [5.5, 4.2, 1.4, 0.2],
       [6. , 3. , 4.8, 1.8],
       [5.8, 2.7, 5.1, 1.9],
       [6. , 2.2, 4. , 1. ],
       [5.4, 3. , 4.5, 1.5],
       [6.2, 3.4, 5.4, 2.3],
       [5.5, 2.3, 4. , 1.3],
       [5.4, 3.9, 1.7, 0.4],
       [5. , 2

In [11]:
# PCA Transformation

In [12]:
pca=PCA(n_components=3)

In [13]:
X_train=pca.fit_transform(X_train)

In [14]:
X_train

array([[-3.19809613e-01, -6.05348170e-01, -3.26338094e-01],
       [ 1.32748645e+00, -1.10665523e-01, -1.69354196e-01],
       [ 1.79450873e+00,  6.14314403e-02,  1.48612379e-01],
       [ 7.92127577e-01,  3.77984923e-01, -3.07968171e-01],
       [ 2.82233703e+00,  7.62500823e-01,  4.33892944e-01],
       [ 2.57313290e-01, -2.43498191e-01,  6.44412424e-02],
       [ 3.29429267e+00,  5.44686773e-01, -3.52148810e-01],
       [ 5.41525286e-01, -3.17525946e-01,  3.09546404e-01],
       [-2.78933480e+00,  4.41451862e-01, -1.32970257e-03],
       [ 3.39404833e+00,  4.59441452e-01, -5.80769348e-01],
       [ 1.14921657e-01, -2.69437408e-01, -2.86655671e-01],
       [-2.74586793e+00,  4.36734540e-01, -1.18396593e-01],
       [-2.87649191e+00,  3.84090975e-01,  1.04412332e-01],
       [-2.30949060e+00,  5.37738148e-01,  3.22150116e-01],
       [-6.51513641e-01, -1.18461155e+00, -3.05080700e-01],
       [ 1.26934877e+00, -1.73732914e-01, -7.48883663e-02],
       [-2.46688042e+00,  7.31965446e-02

In [16]:
X_test=pca.transform(X_test)

In [17]:
X_test

array([[ 0.80439876, -0.13543896, -0.24737538],
       [-2.29309026,  0.98634486, -0.0784158 ],
       [ 3.68433622,  0.24731506, -0.52549519],
       [ 0.69649493, -0.12248592,  0.0255966 ],
       [ 1.22118762,  0.29079438, -0.51985437],
       [-2.51491704,  0.53003897, -0.11273739],
       [-0.29304377, -0.19345013,  0.08669751],
       [ 1.81593071,  0.42104585,  0.12660806],
       [ 0.81492503, -0.48843608, -0.51573345],
       [ 0.01494263, -0.25098762, -0.18642688],
       [ 1.55433487,  0.25664806,  0.24352899],
       [-2.90488328, -0.10460692, -0.19731934],
       [-2.726196  ,  0.72723396, -0.22940215],
       [-2.78848338,  0.01384299, -0.18594583],
       [-2.68715898,  0.62570812,  0.24422624],
       [ 0.98940584,  0.31339181,  0.17127077],
       [ 2.23673859, -0.04245912,  0.27093634],
       [-0.08233607, -0.51655131, -0.2537264 ],
       [ 0.5202073 , -0.37311822,  0.01968768],
       [ 2.04110639, -0.21277316,  0.19256168],
       [-2.7480442 , -0.07767852,  0.047

In [18]:
pca.components_

array([[ 0.37167593, -0.06299273,  0.85531578,  0.35542065],
       [ 0.66585782,  0.71303104, -0.19438974, -0.10214078],
       [-0.55627639,  0.61439252,  0.05561896,  0.55676291]])

In [19]:
pca.explained_variance_ratio_

array([0.9191876 , 0.05549301, 0.02010131])